/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import libreriacarolina.Conexion;
//import java.awt.event.KeyEvent;
//import java.sql.PreparedStatement;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import java.sql.SQLException;

/**
 *
 * @author Victor
 */
public class frmClientes extends javax.swing.JInternalFrame {
    Connection conn ;
    DefaultTableModel model;
    
    /**
     * Creates new form frmClientes
     */
    public frmClientes() {
        initComponents();
        try
        {
              Class.forName("org.gjt.mm.mysql.Driver") ;
              conn = DriverManager.getConnection("jdbc:mysql://localhost/libreria","root","") ;
              //System.out.println("Conexion en CLIENTES");
        }
        catch(Exception e) {}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscart = new javax.swing.JButton();

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Codigo, Nombre o Apellido");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Apellido", "Nombre", "NRE"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/preview.png"))); // NOI18N
        btnBuscart.setText("Mostrar todos los clientes ");
        btnBuscart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscart)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigo)
                        .addComponent(btnBuscar)
                        .addComponent(btnBuscart)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String data = txtBuscar.getText();
        String sql = "";    
        try {
            sql="SELECT * FROM clientes WHERE id_cliente ='"+data+"' OR apellidos ='"+data+"' OR nombres ='"+data+"' OR nre ='"+data+"'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql) ;
            model = (DefaultTableModel) this.tblClientes.getModel();
            model.setRowCount(0);
            Object Datos[] = new Object[4];
                while (rs.next()){
                    for (int i=0;i<4;i++) Datos[i]=rs.getObject(i+1);
                        model.addRow(Datos);
                }
                this.tblClientes.setModel(model);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: "+e.toString(), " ¡¡ ERROR !!", JOptionPane.ERROR_MESSAGE);
        }
        txtBuscar.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        String data = txtBuscar.getText();
        String sql = "";    
        try {
            sql="SELECT * FROM clientes WHERE id_cliente LIKE '%"+data+"%' OR apellidos LIKE '%"+data+"%' OR nombres LIKE '%"+data+"%' OR nre LIKE '%"+data+"%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql) ;
            model = (DefaultTableModel) this.tblClientes.getModel();
            model.setRowCount(0);
            Object Datos[] = new Object[4];
                while (rs.next()){
                    for (int i=0;i<4;i++) Datos[i]=rs.getObject(i+1);
                        model.addRow(Datos);
                }
                this.tblClientes.setModel(model);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: "+e.toString(), " ¡¡ ERROR !!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscartActionPerformed
        // TODO add your handling code here:
        String sql = "";    
        try {
            sql = "SELECT * FROM clientes";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql) ;
            model = (DefaultTableModel) this.tblClientes.getModel();
            model.setRowCount(0);
            Object Datos[] = new Object[4];
                while (rs.next()){
                    for (int i=0;i<4;i++) Datos[i]=rs.getObject(i+1);
                        model.addRow(Datos);
                }
                this.tblClientes.setModel(model);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error: "+e.toString(), " ¡¡ ERROR !!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBuscartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscart;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
